# Duplicate Data Removal Using Pandas

## Objective

To identify duplicate records in a dataset and remove them using Pandas. Compare the number of rows before and after cleaning to understand the importance of data cleaning.

In [3]:
import pandas as pd

data = {
    "Name": ["Arun", "Premi", "Kavin", "Dharani", "Arun", "Premi", "rohi", "yas"],
    "Age": [21, 22, 23, 21, 21, 22, 24, 23, ],
    "Marks": [85, 90, 78, 88, 85, 90, 95, 88],
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

print("Original Row Count:", len(df))

Original Dataset:

      Name  Age  Marks
0     Arun   21     85
1    Premi   22     90
2    Kavin   23     78
3  Dharani   21     88
4     Arun   21     85
5    Premi   22     90
6     rohi   24     95
7      yas   23     88

Original Row Count: 8

In [4]:
duplicates = df.duplicated()

print("Duplicate Records:")
display(df[duplicates])

print("Number of Duplicate Records:", duplicates.sum())

Duplicate Records:

    Name  Age  Marks
4   Arun   21     85
5  Premi   22     90

Number of Duplicate Records: 2

In [5]:
cleaned_df = df.drop_duplicates()

print("Cleaned Dataset:")
display(cleaned_df)

print("Rows After Cleaning:", len(cleaned_df))

Cleaned Dataset:

      Name  Age  Marks
0     Arun   21     85
1    Premi   22     90
2    Kavin   23     78
3  Dharani   21     88
6     rohi   24     95
7      yas   23     88

Rows After Cleaning: 6

In [7]:
before_cleaning = len(df)
after_cleaning = len(cleaned_df)
removed_rows = before_cleaning - after_cleaning

print("Before Cleaning:", before_cleaning)
print("After Cleaning:", after_cleaning)
print("Duplicate Rows Removed:", removed_rows)

Before Cleaning: 8
After Cleaning: 6
Duplicate Rows Removed: 2

In [8]:
remaining_duplicates = cleaned_df.duplicated().sum()

print("Remaining Duplicate Records:", remaining_duplicates)

if remaining_duplicates == 0:
    print("Dataset is clean. No duplicate rows remain.")
else:
    print("Duplicate rows still exist.")

Remaining Duplicate Records: 0
Dataset is clean. No duplicate rows remain.

In [9]:
print("Duplicate Data Removal Report")
print("-----------------------------")
print("Original Rows:", len(df))
print("Duplicate Rows Found:", int(df.duplicated().sum()))
print("Rows After Cleaning:", len(cleaned_df))
print("Rows Removed:", removed_rows)
print("Remaining Duplicates:", int(cleaned_df.duplicated().sum()))

Duplicate Data Removal Report
-----------------------------
Original Rows: 8
Duplicate Rows Found: 2
Rows After Cleaning: 6
Rows Removed: 2
Remaining Duplicates: 0

## Observations

1. The original dataset contains 7 rows and 3 columns.
2. Two duplicate records were identified using `duplicated()`.
3. The `drop_duplicates()` function removed the repeated records.
4. The cleaned dataset contains 5 rows.
5. The dataset has no duplicate rows after cleaning.

## Conclusion

Duplicate data removal is an important data-cleaning technique. Duplicate records can affect data analysis and may lead to misleading results. Pandas provides `duplicated()` to identify duplicate rows and `drop_duplicates()` to remove them.